### ISSUE TITLE
[BUG] [DistributeSpaceWarper] Exception occurred when running on game version [0.9.26.13034]

### ISSUE THREAD

**Issue by DaniilIonov** [Fireball14/DSP-Mods#14]
This exception is seen when enabling the mod on the [0.9.26.13034] game version.
![image](https://user-images.githubusercontent.com/35689903/174690332-f0ee089b-1397-4b0e-a441-bcbac3976876.png)

Also, [BetterLogisticsStations] [v1.0.2] is installed and [PlanetaryLogisticsStationMaxItemKinds] is set to 6.

**Comment by Fireball14** [comment]
Hey, im not playing dsp right now, could you comment here in few days. So i don't forget to fix it? As for now, try to save a game in to a different save, close it completely, and than restart game and load that new save. It helped me before.

**Comment by DaniilIonov** [comment]
Thank you! A separate save file seems to fix this issue, no longer see the exception.

There is an additional issue: warpers are not getting added to the demanding station, drones and vessels just fly into the station and do not add warpers. But that might require a separate ticket to track.

**Comment by Fireball14** [comment]
Hey, I found what was causing red text to appear. In my case it was mod "NoPrologue by ctcDNightmare".
It is not needed anyway since devs added "Skip prologue" button in menu.
My mods dose not appear to cause any red text. So il close this issue. If they are not working pls create new issue and upload your save somewhere so I could test what's going on.
