### ISSUE TITLE
Not compatible with latest game version

### ISSUE THREAD

**Issue by SBeausoleil** [Fireball14/DSP-Mods#16]
Since the Semptember Update, new ILS do not have the 6th slot for warpers anymore.

**Comment by hansonmi** [comment]
> Since the Semptember Update, new ILS do not have the 6th slot for warpers anymore.

for me ILS that were placed using the mod prior to the update still have the 7th slot, however, the ILS that is the one that received the warpers and distributes them to all other ILS will not stop requesting them in slots 1-5. If setting an ILS slot 1-5 as a local or remote demand they keep getting them regardless of caps and my ILS ended up with over 200k warpers in a slot.

The fix was to delete any previously placed ILS and replace it with one that didn't have the hidden slots

**Comment by Fireball14** [comment]
Fixed it.
